version: "3.1"

services:
  frontend:
    container_name: awesome
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 5000:5000
    command: npm run dev
